# Generated by Django 4.0.5 on 2022-06-25 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_alter_recipe_image_alter_recipe_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='video',
        ),
        migrations.AddField(
            model_name='recipe',
            name='video_url',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
