# Generated by Django 4.0.5 on 2022-07-22 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0003_remove_recipe_video_recipe_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='video',
            field=models.FileField(blank=True, upload_to='videos/'),
        ),
    ]
