# Generated by Django 4.0.5 on 2022-07-29 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0004_recipe_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='video_url',
        ),
    ]
